# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.IntegerField(default=None, null=True)),
                ('humidity', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
