# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
