# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wth', '0004_auto_20161120_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
